theme: jekyll-theme-minimal
title: Changhun Jo
description: Ph. D. candidate at UW-Madison
logo: https://lh5.googleusercontent.com/RvkaHxemmCqVveROQktdL2IlErfikbKZdzGRe0rct_RGV2U9Jkrmea_n6d7Mz5v0bC0plZOyjcoRCrGdvC5dGTPViyiZDsjY-FmRvXXU92RvMtgz_HHgHaqeBTaKvfFx3w=w1280
show_downloads: false
